---
- name:
  hosts: db
  become: true
  tasks:
    - name: Add apt key
      apt_key:
        id: D68FA50FEA312927
        keyserver: keyserver.ubuntu.com
    
    - name: Add apt repository
      apt_repository: 
        repo: deb [ arch=amd64,arm64 ] http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
        state: present
    
    - name: Install mongodb
      apt: 
        name: mongodb-org
        state: present
    
    - name: Start service
      systemd:
        name: mongod
        enabled: yes
